name: Release chart test

on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTION"
          git config user.email "$GITHUB_ACTION@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Add Helm repos
        run: |
          helm repo add harness-helm https://harness.github.io/helm-charts
          helm repo add harness-common https://harness.github.io/helm-common
          helm repo add bitnami https://charts.bitnami.com/bitnami
      
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.0.0
        with:
          version: 'v4.28.1'

      - name: Override values.yaml for demo
        run: |
          yq '. *= load("override.yaml")' values.yaml > tmp.values
          mv tmp.values values.yaml
          rm tmp.values
      
      - name: Run Chart Releaser demo
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: src
          charts_repo_url: "${{ inputs.repo }}"
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      
