name: Release chart demo and prod

on:
  push:
    branches:
      - "main"
    paths:
      - '**.yaml'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTION"
          git config user.email "$GITHUB_ACTION@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Add Helm repos
        run: |
          helm repo add harness-helm https://harness.github.io/helm-charts
          helm repo add harness-common https://harness.github.io/helm-common
          helm repo add bitnami https://charts.bitnami.com/bitnami
      
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.0.0
        with:
          version: 'v4.28.1'

      - name: Override values.yaml and Chart.yaml for demo
        run: |
          yq '. *= load("src/override-demo.yaml")' src/harness/values.yaml > tmp.values
          mv tmp.values src/harness/values.yaml
          yq -i '.name += "-demo"' src/harness/Chart.yaml
      
      - name: Run Chart Releaser demo
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: src
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Override values.yaml and Chart.yaml for prod
        run: |
          yq '. *= load("src/override-prod.yaml")' src/harness/values.yaml > tmp.values
          mv tmp.values src/harness/values.yaml
          yq -i '.name += "-prod"' src/harness/Chart.yaml
      
      - name: Run Chart Releaser prod
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: src
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
